# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1146, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mapping = QtWidgets.QLabel(self.centralwidget)
        self.mapping.setGeometry(QtCore.QRect(370, 10, 41, 16))
        self.mapping.setObjectName("mapping")
        self.tableWidget_pick = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_pick.setGeometry(QtCore.QRect(820, 30, 311, 621))
        self.tableWidget_pick.setObjectName("tableWidget_pick")
        self.tableWidget_pick.setColumnCount(4)
        self.tableWidget_pick.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget_pick.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget_pick.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget_pick.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pick.setHorizontalHeaderItem(3, item)
        self.comp_dis = QtWidgets.QLabel(self.centralwidget)
        self.comp_dis.setGeometry(QtCore.QRect(370, 410, 91, 16))
        self.comp_dis.setObjectName("comp_dis")
        self.image_plot = QtWidgets.QPushButton(self.centralwidget)
        self.image_plot.setGeometry(QtCore.QRect(760, 10, 41, 21))
        self.image_plot.setObjectName("image_plot")
        self.line_plot = QtWidgets.QPushButton(self.centralwidget)
        self.line_plot.setGeometry(QtCore.QRect(760, 410, 41, 21))
        self.line_plot.setObjectName("line_plot")
        self.combo_Element = QtWidgets.QComboBox(self.centralwidget)
        self.combo_Element.setGeometry(QtCore.QRect(690, 10, 69, 21))
        self.combo_Element.setObjectName("combo_Element")
        self.combo_Element.addItem("")
        self.combo_Element.addItem("")
        self.combo_Element.addItem("")
        self.combo_Element.addItem("")
        self.combo_Colormap = QtWidgets.QComboBox(self.centralwidget)
        self.combo_Colormap.setGeometry(QtCore.QRect(620, 10, 69, 21))
        self.combo_Colormap.setObjectName("combo_Colormap")
        self.combo_Colormap.addItem("")
        self.combo_Colormap.addItem("")
        self.combo_Colormap.addItem("")
        self.combo_Colormap.addItem("")
        self.combo_Colormap.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 331, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.combo_DataElement = QtWidgets.QComboBox(self.centralwidget)
        self.combo_DataElement.setGeometry(QtCore.QRect(240, 10, 69, 21))
        self.combo_DataElement.setObjectName("combo_DataElement")
        self.combo_DataElement.addItem("")
        self.combo_DataElement.addItem("")
        self.combo_DataElement.addItem("")
        self.combo_DataElement.addItem("")
        self.datashow = QtWidgets.QPushButton(self.centralwidget)
        self.datashow.setGeometry(QtCore.QRect(310, 10, 41, 21))
        self.datashow.setObjectName("datashow")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 450, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 31, 20))
        self.label_2.setObjectName("label_2")
        self.ternary_plot = QtWidgets.QPushButton(self.centralwidget)
        self.ternary_plot.setGeometry(QtCore.QRect(310, 450, 41, 21))
        self.ternary_plot.setObjectName("ternary_plot")
        self.ternary_plot_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.ternary_plot_2.setGeometry(QtCore.QRect(20, 470, 331, 331))
        self.ternary_plot_2.setObjectName("ternary_plot_2")
        self.combo_ViewOrder = QtWidgets.QComboBox(self.centralwidget)
        self.combo_ViewOrder.setGeometry(QtCore.QRect(230, 450, 81, 22))
        self.combo_ViewOrder.setObjectName("combo_ViewOrder")
        self.combo_ViewOrder.addItem("")
        self.combo_ViewOrder.addItem("")
        self.combo_ViewOrder.addItem("")
        self.combo_ViewOrder.addItem("")
        self.combo_ViewOrder.addItem("")
        self.combo_ViewOrder.addItem("")
        self.combo_ViewOrder.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(820, 10, 71, 21))
        self.label_3.setObjectName("label_3")
        self.combo_E1 = QtWidgets.QComboBox(self.centralwidget)
        self.combo_E1.setGeometry(QtCore.QRect(60, 10, 41, 22))
        self.combo_E1.setObjectName("combo_E1")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.addItem("")
        self.combo_E1.setItemText(10, "")
        self.combo_E2 = QtWidgets.QComboBox(self.centralwidget)
        self.combo_E2.setGeometry(QtCore.QRect(100, 10, 41, 22))
        self.combo_E2.setObjectName("combo_E2")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.addItem("")
        self.combo_E2.setItemText(10, "")
        self.combo_E3 = QtWidgets.QComboBox(self.centralwidget)
        self.combo_E3.setGeometry(QtCore.QRect(140, 10, 41, 22))
        self.combo_E3.setObjectName("combo_E3")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.addItem("")
        self.combo_E3.setItemText(10, "")
        self.image = QtWidgets.QWidget(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(370, 30, 431, 371))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(0, 0, 0);")
        self.image.setObjectName("image")
        self.line = QtWidgets.QGraphicsView(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(370, 430, 431, 371))
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 21))
        self.menubar.setObjectName("menubar")
        self.menuFirst_Designer = QtWidgets.QMenu(self.menubar)
        self.menuFirst_Designer.setObjectName("menuFirst_Designer")
        self.menuImage = QtWidgets.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionImport_folder = QtWidgets.QAction(MainWindow)
        self.actionImport_folder.setObjectName("actionImport_folder")
        self.actionImport_file = QtWidgets.QAction(MainWindow)
        self.actionImport_file.setObjectName("actionImport_file")
        self.actionExport_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_2.setObjectName("actionExport_2")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExport_Image = QtWidgets.QAction(MainWindow)
        self.actionExport_Image.setObjectName("actionExport_Image")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFirst_Designer.addAction(self.actionImport_folder)
        self.menuFirst_Designer.addAction(self.actionImport_file)
        self.menuFirst_Designer.addAction(self.actionExport)
        self.menuFirst_Designer.addAction(self.actionExit)
        self.menuImage.addAction(self.actionExport_Image)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFirst_Designer.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mapping.setText(_translate("MainWindow", "Mapping"))
        item = self.tableWidget_pick.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "E1"))
        item = self.tableWidget_pick.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "E2"))
        item = self.tableWidget_pick.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "E3"))
        item = self.tableWidget_pick.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "line_number"))
        self.comp_dis.setText(_translate("MainWindow", "Comp-Dis Profile"))
        self.image_plot.setText(_translate("MainWindow", "Plot"))
        self.line_plot.setText(_translate("MainWindow", "Plot"))
        self.combo_Element.setItemText(0, _translate("MainWindow", "Element"))
        self.combo_Element.setItemText(1, _translate("MainWindow", "E1"))
        self.combo_Element.setItemText(2, _translate("MainWindow", "E2"))
        self.combo_Element.setItemText(3, _translate("MainWindow", "E3"))
        self.combo_Colormap.setItemText(0, _translate("MainWindow", "Colormap"))
        self.combo_Colormap.setItemText(1, _translate("MainWindow", "gist_ncar"))
        self.combo_Colormap.setItemText(2, _translate("MainWindow", "gist_rainbow"))
        self.combo_Colormap.setItemText(3, _translate("MainWindow", "nipy_spectral"))
        self.combo_Colormap.setItemText(4, _translate("MainWindow", "gist_stern"))
        self.combo_DataElement.setItemText(0, _translate("MainWindow", "Element"))
        self.combo_DataElement.setItemText(1, _translate("MainWindow", "E1"))
        self.combo_DataElement.setItemText(2, _translate("MainWindow", "E2"))
        self.combo_DataElement.setItemText(3, _translate("MainWindow", "E3"))
        self.datashow.setText(_translate("MainWindow", "Show"))
        self.label.setText(_translate("MainWindow", "Ternary View"))
        self.label_2.setText(_translate("MainWindow", "Data"))
        self.ternary_plot.setText(_translate("MainWindow", "Plot"))
        self.combo_ViewOrder.setItemText(0, _translate("MainWindow", "View order"))
        self.combo_ViewOrder.setItemText(1, _translate("MainWindow", "123"))
        self.combo_ViewOrder.setItemText(2, _translate("MainWindow", "132"))
        self.combo_ViewOrder.setItemText(3, _translate("MainWindow", "213"))
        self.combo_ViewOrder.setItemText(4, _translate("MainWindow", "231"))
        self.combo_ViewOrder.setItemText(5, _translate("MainWindow", "312"))
        self.combo_ViewOrder.setItemText(6, _translate("MainWindow", "321"))
        self.label_3.setText(_translate("MainWindow", "Tie line data"))
        self.combo_E1.setItemText(0, _translate("MainWindow", "E1"))
        self.combo_E1.setItemText(1, _translate("MainWindow", "Al"))
        self.combo_E1.setItemText(2, _translate("MainWindow", "Co"))
        self.combo_E1.setItemText(3, _translate("MainWindow", "Cr"))
        self.combo_E1.setItemText(4, _translate("MainWindow", "Cu"))
        self.combo_E1.setItemText(5, _translate("MainWindow", "Fe"))
        self.combo_E1.setItemText(6, _translate("MainWindow", "Nb"))
        self.combo_E1.setItemText(7, _translate("MainWindow", "Ni"))
        self.combo_E1.setItemText(8, _translate("MainWindow", "Ta"))
        self.combo_E1.setItemText(9, _translate("MainWindow", "W"))
        self.combo_E2.setItemText(0, _translate("MainWindow", "E2"))
        self.combo_E2.setItemText(1, _translate("MainWindow", "Al"))
        self.combo_E2.setItemText(2, _translate("MainWindow", "Co"))
        self.combo_E2.setItemText(3, _translate("MainWindow", "Cr"))
        self.combo_E2.setItemText(4, _translate("MainWindow", "Cu"))
        self.combo_E2.setItemText(5, _translate("MainWindow", "Fe"))
        self.combo_E2.setItemText(6, _translate("MainWindow", "Nb"))
        self.combo_E2.setItemText(7, _translate("MainWindow", "Ni"))
        self.combo_E2.setItemText(8, _translate("MainWindow", "Ta"))
        self.combo_E2.setItemText(9, _translate("MainWindow", "W"))
        self.combo_E3.setItemText(0, _translate("MainWindow", "E3"))
        self.combo_E3.setItemText(1, _translate("MainWindow", "Al"))
        self.combo_E3.setItemText(2, _translate("MainWindow", "Co"))
        self.combo_E3.setItemText(3, _translate("MainWindow", "Cr"))
        self.combo_E3.setItemText(4, _translate("MainWindow", "Cu"))
        self.combo_E3.setItemText(5, _translate("MainWindow", "Fe"))
        self.combo_E3.setItemText(6, _translate("MainWindow", "Nb"))
        self.combo_E3.setItemText(7, _translate("MainWindow", "Ni"))
        self.combo_E3.setItemText(8, _translate("MainWindow", "Ta"))
        self.combo_E3.setItemText(9, _translate("MainWindow", "W"))
        self.menuFirst_Designer.setTitle(_translate("MainWindow", "File"))
        self.menuImage.setTitle(_translate("MainWindow", "Image"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionImport_folder.setText(_translate("MainWindow", "Import folder"))
        self.actionImport_file.setText(_translate("MainWindow", "Import file"))
        self.actionExport_2.setText(_translate("MainWindow", "Export"))
        self.actionDocumentation.setText(_translate("MainWindow", "Online Documentation"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExport_Image.setText(_translate("MainWindow", "Export Image"))
        self.actionExport.setText(_translate("MainWindow", "Export data"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

